### ISSUE TITLE
Upgrading from v1.6.2 to v1.7.0 shows different -D output

### ISSUE THREAD

**Issue by felker** [hunspell/hunspell#608]
I had no idea that a new version of Hunspell was released until I ran `brew upgrade`; congrats 🎉 

I was surprised to see that the output of `hunspell -D` changed from my previous version 1.6.2, and I am somewhat concerned, because it stopped working in my Emacs setup. I was able to fix the Emacs integration, but now I am worried that my dictionaries are no longer loading correctly. 

Before:
```
SEARCH PATH:
...
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/Users/kfelker/Library/Spelling/en_ZA
/Users/kfelker/Library/Spelling/en_CA
/Users/kfelker/Library/Spelling/hyph_en_US
/Users/kfelker/Library/Spelling/en_GB
/Users/kfelker/Library/Spelling/hyph_en_GB
/Users/kfelker/Library/Spelling/en_AU
/Users/kfelker/Library/Spelling/en_US
LOADED DICTIONARY:
/Users/kfelker/Library/Spelling/en_US.aff
/Users/kfelker/Library/Spelling/en_US.dic
Hunspell 1.6.2
```
After:

```
SEARCH PATH:
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/Users/kfelker/Library/Spelling/en_ZA
/Users/kfelker/Library/Spelling/en_CA
/Users/kfelker/Library/Spelling/hyph_en_US
/Users/kfelker/Library/Spelling/en_GB
/Users/kfelker/Library/Spelling/hyph_en_GB
/Users/kfelker/Library/Spelling/en_AU
/Users/kfelker/Library/Spelling/en_US
```
As you can see, `LOADED DICTIONARIES:` and the verision info are now missing. Glancing at the source code, it seems like they should still be output: https://github.com/hunspell/hunspell/blob/master/src/tools/hunspell.cxx

and I didn't see any mentions in the release notes. 

Should I be concerned about this, or is this normal/intended?

**Comment by luis-henrix** [comment]
I believe this is fixed in GNU Emacs git tree with commit 2925ce5a7ec1 ("Support Hunspell 1.7.0 in ispell.el").

**Comment by felker** [comment]
thanks! I can see that the Emacs commit from 2018-11-26 has an illustrative comment:

```
@@ -1113,7 +1113,12 @@ dictionary from that list was found."
                                 null-device
                                 t
                                 nil
-                                "-D")
+                                 ;; Hunspell 1.7.0 (and later?) won't
+                                 ;; show LOADED DICTIONARY unless
+                                 ;; there's at least one file argument
+                                 ;; on the command line.  So we feed
+                                 ;; it with the null device.
+                                "-D" null-device)
            (buffer-string))
          "[\n\r]+"
          t))
```

I can confirm that `hunspell -D file.txt` does show the `LOADED DICTIONARIES:` after it finishes with the file. This should probably be added to the Hunspell release notes; I will let someone else close this issue if they see fit.

**Comment by omajid** [comment]
A PR to fix this issue was opened a in November: https://github.com/hunspell/hunspell/pull/607. Can that be merged, please?

**Comment by wxie2017** [comment]
The error still happened under GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-27:
ispell-find-hunspell-dictionaries: Can’t find Hunspell dictionary with a .aff affix file [2 times]

more information:
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.0)

hunspell -D
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/usr/share/hunspell/en_US
/usr/share/hunspell/en_US-large
/usr/share/myspell/dicts/en_US
/usr/share/myspell/dicts/en_US-large

ispell-hunspell-dict-paths-alist is a variable defined in ‘ispell.el’.
Its value is
(("american" #1="/usr/share/hunspell/en_US.aff")
 ("english" #1#)
 ("en_US-large" "/usr/share/hunspell/en_US-large.aff")
 ("en_US" #1#))

ispell-hunspell-dictionary-alist is a variable defined in ‘ispell.el’.
Its value is nil

hunspell -d
Can't open affix or dictionary files for dictionary named "zh_CN".

**Comment by wxie2017** [comment]
fixed by
```
cd /usr/share/hunspell
sudo ln -sf en_US-large.aff zh_CN.aff
sudo ln -sf en_US-large.dic zh_CN.dic
```

**Comment by sergeyklay** [comment]
This issue was fixed by https://github.com/hunspell/hunspell/pull/607 and may be closed. 

/cc @caolanm

**Comment by caolanm** [comment]
thanks @sergeyklay
